<use f='include/llvm-7/llvm/Support/Error.h' l='189' u='c' c='_ZN4llvm5ErrorC1EOS0_'/>
<def f='include/llvm-7/llvm/Support/Error.h' l='206' ll='219' type='llvm::Error &amp; llvm::Error::operator=(llvm::Error &amp;&amp; Other)'/>
<use f='include/llvm-7/llvm/Support/Error.h' l='1022' u='c' c='_ZN4llvm19ErrorAsOutParameterD1Ev'/>
<doc f='include/llvm-7/llvm/Support/Error.h' l='202'>/// Move-assign an error value. The current error must represent success, you
  /// you cannot overwrite an unhandled error. The current error is then
  /// considered unchecked. The source error becomes a checked success value,
  /// regardless of its original state.</doc>
