<def f='include/llvm-7/llvm/Support/Error.h' l='187' ll='190' type='void llvm::Error::Error(llvm::Error &amp;&amp; Other)'/>
<use f='include/llvm-7/llvm/Support/Error.h' l='387' u='c' c='_ZN4llvm9ErrorList4joinENS_5ErrorES1_'/>
<use f='include/llvm-7/llvm/Support/Error.h' l='389' u='c' c='_ZN4llvm9ErrorList4joinENS_5ErrorES1_'/>
<use f='include/llvm-7/llvm/Support/Error.h' l='400' u='c' c='_ZN4llvm9ErrorList4joinENS_5ErrorES1_'/>
<use f='include/llvm-7/llvm/Support/Error.h' l='405' u='c' c='_ZN4llvm9ErrorList4joinENS_5ErrorES1_'/>
<use f='include/llvm-7/llvm/Support/Error.h' l='418' u='c' c='_ZN4llvm10joinErrorsENS_5ErrorES0_'/>
<use f='include/llvm-7/llvm/Support/Error.h' l='418' u='c' c='_ZN4llvm10joinErrorsENS_5ErrorES0_'/>
<use f='include/llvm-7/llvm/Support/Error.h' l='550' u='c' c='_ZN4llvm8Expected9takeErrorEv'/>
<use f='include/llvm-7/llvm/Support/Error.h' l='785' u='c' c='_ZN4llvm18ErrorHandlerTraitsIRFvRT_EE5applyEOT_St10unique_ptrINS_13ErrorInfoBaseESt14default_deleteIS9_EE'/>
<use f='include/llvm-7/llvm/Support/Error.h' l='818' u='c' c='_ZN4llvm18ErrorHandlerTraitsIRFvSt10unique_ptrIT_St14default_deleteIS2_EEEE5applyEOT_S1_INS_13ErrorInfoBaseES3_ISB_EE'/>
<use f='include/llvm-7/llvm/Support/Error.h' l='877' u='c' c='_ZN4llvm12handleErrorsENS_5ErrorEDpOT_'/>
<use f='include/llvm-7/llvm/Support/Error.h' l='905' u='c' c='_ZN4llvm15handleAllErrorsENS_5ErrorE'/>
<use f='include/llvm-7/llvm/Support/Error.h' l='958' u='c' c='_ZN4llvm8toStringB5cxx11ENS_5ErrorE'/>
<use f='include/llvm-7/llvm/Support/Error.h' l='972' u='c' c='_ZN4llvm12consumeErrorENS_5ErrorE'/>
<use f='include/llvm-7/llvm/Support/Error.h' l='983' u='c' c='_ZN4llvm11errorToBoolENS_5ErrorE'/>
<use f='include/llvm-7/llvm/Support/Error.h' l='1157' u='c' c='_ZNK4llvm11ExitOnErrorclENS_5ErrorE'/>
<use f='include/llvm-7/llvm/Support/Error.h' l='1177' u='c' c='_ZNK4llvm11ExitOnError10checkErrorENS_5ErrorE'/>
<doc f='include/llvm-7/llvm/Support/Error.h' l='184'>/// Move-construct an error value. The newly constructed error is considered
  /// unchecked, even if the source error had been checked. The original error
  /// becomes a checked Success value, regardless of its original state.</doc>
